use serde::Deserialize;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const DEFAULT_OUTPUT: &str = "crates/predicates/src/nat/nationalities.rs";

#[derive(Deserialize)]
struct Country {
    name: String,
    #[serde(rename = "alpha-3")]
    alpha3: String,
    #[serde(rename = "country-code", deserialize_with = "deserialize_numeric_code")]
    numeric: u32,
}

fn deserialize_numeric_code<'de, D: serde::Deserializer<'de>>(d: D) -> Result<u32, D::Error> {
    let s = String::deserialize(d)?;
    s.parse().map_err(serde::de::Error::custom)
}

/// Converts a country name into a valid PascalCase Rust identifier.
/// Replaces common diacritics with ASCII equivalents, then capitalises
/// the first letter of each word and drops all remaining non-alphanumeric chars.
fn to_variant_name(name: &str) -> String {
    let mut ascii = String::with_capacity(name.len());
    for c in name.chars() {
        let replacement = match c {
            'À' | 'Á' | 'Â' | 'Ã' | 'Ä' | 'Å' | 'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' => 'a',
            'È' | 'É' | 'Ê' | 'Ë' | 'è' | 'é' | 'ê' | 'ë' => 'e',
            'Ì' | 'Í' | 'Î' | 'Ï' | 'ì' | 'í' | 'î' | 'ï' => 'i',
            'Ò' | 'Ó' | 'Ô' | 'Õ' | 'Ö' | 'ò' | 'ó' | 'ô' | 'õ' | 'ö' => 'o',
            'Ù' | 'Ú' | 'Û' | 'Ü' | 'ù' | 'ú' | 'û' | 'ü' => 'u',
            'Ç' | 'ç' => 'c',
            'Ñ' | 'ñ' => 'n',
            'Ý' | 'ý' => 'y',
            c if c.is_ascii() => c,
            _ => continue,
        };
        ascii.push(replacement);
    }

    ascii
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn get_flag(args: &[String], flag: &str) -> Option<String> {
    args.windows(2)
        .find(|w| w[0] == flag)
        .map(|w| w[1].clone())
}

fn usage() -> ! {
    eprintln!("usage: iso-preset <url> [--output <path>]");
    eprintln!("  --output  destination file (default: {DEFAULT_OUTPUT})");
    eprintln!();
    eprintln!("example:");
    eprintln!("  iso-preset https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/slim-3/slim-3.json");
    std::process::exit(1);
}

fn generate(countries: &[Country], from_url: String) -> String {
    let mut out = String::new();
    out.push_str("use strum::EnumIter;\n\n");
    out.push_str("/// ISO 3166-1 nationality codes. Generated by `iso-preset`.\n");
    out.push_str("/// Discriminant equals the numeric country code.\n");
    out.push_str("///\n");
    out.push_str(format!("/// Data retrieved from <{}>.\n", from_url).as_str());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter)]\n");
    out.push_str("#[repr(u32)]\n");
    out.push_str("pub enum Nationality {\n");
    for c in countries {
        let variant = to_variant_name(&c.name);
        out.push_str(&format!("    /// {} ({})\n", c.name, c.alpha3));
        out.push_str(&format!("    {variant} = {},\n", c.numeric));
    }
    out.push_str("}\n");
    out
}

fn write_output(content: &str, path: &Path) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap_or_else(|e| {
            eprintln!("error creating directories {}: {e}", parent.display());
            std::process::exit(1);
        });
    }
    let mut file = fs::File::create(path).unwrap_or_else(|e| {
        eprintln!("error creating {}: {e}", path.display());
        std::process::exit(1);
    });
    file.write_all(content.as_bytes()).unwrap_or_else(|e| {
        eprintln!("error writing {}: {e}", path.display());
        std::process::exit(1);
    });
    eprintln!("written to {}", path.display());
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let url = args.first().unwrap_or_else(|| usage()).clone();
    let output: PathBuf = get_flag(&args, "--output")
        .unwrap_or_else(|| DEFAULT_OUTPUT.to_string())
        .into();

    let data = ureq::get(&url)
        .call()
        .unwrap_or_else(|e| {
            eprintln!("error fetching {url}: {e}");
            std::process::exit(1);
        })
        .body_mut()
        .read_to_string()
        .unwrap_or_else(|e| {
            eprintln!("error reading response body: {e}");
            std::process::exit(1);
        });

    let mut countries: Vec<Country> = serde_json::from_str(&data).unwrap_or_else(|e| {
        eprintln!("error parsing JSON: {e}");
        std::process::exit(1);
    });

    countries.sort_by_key(|c| c.numeric);

    write_output(&generate(&countries, url), &output);
}
