[workspace]
members = [
    "crates/air-core",
    "crates/stwo-sha256",
    "crates/eu-id-prover",
    "crates/sdk",
    "crates/stwo-keccak",
    "crates/stwo-mldsa",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1

[workspace.dependencies]
stwo = { git = "https://github.com/0xLucqs/stwo.git", rev = "4f39939eacd0c5efc8ee157e4215a250ca29168f", features = ["prover"] }
stwo-constraint-framework = { git = "https://github.com/0xLucqs/stwo.git", rev = "4f39939eacd0c5efc8ee157e4215a250ca29168f", features = ["prover"] }
stwo-air-utils = { git = "https://github.com/0xLucqs/stwo.git", rev = "4f39939eacd0c5efc8ee157e4215a250ca29168f" }
stwo-air-utils-derive = { git = "https://github.com/0xLucqs/stwo.git", rev = "4f39939eacd0c5efc8ee157e4215a250ca29168f" }
serde = { version = "1", features = ["derive"] }
num-traits = "0.2"

# All workspace crates use these Clippy settings.
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
