use strum::EnumIter;

/// ISO 3166-1 nationality codes. Generated by `iso-preset`.
/// Discriminant equals the numeric country code.
///
/// Data retrieved from <https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/refs/heads/master/slim-3/slim-3.json>.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter)]
#[repr(u32)]
pub enum Nationality {
    /// Afghanistan (AFG)
    Afghanistan = 4,
    /// Albania (ALB)
    Albania = 8,
    /// Antarctica (ATA)
    Antarctica = 10,
    /// Algeria (DZA)
    Algeria = 12,
    /// American Samoa (ASM)
    AmericanSamoa = 16,
    /// Andorra (AND)
    Andorra = 20,
    /// Angola (AGO)
    Angola = 24,
    /// Antigua and Barbuda (ATG)
    AntiguaAndBarbuda = 28,
    /// Azerbaijan (AZE)
    Azerbaijan = 31,
    /// Argentina (ARG)
    Argentina = 32,
    /// Australia (AUS)
    Australia = 36,
    /// Austria (AUT)
    Austria = 40,
    /// Bahamas (BHS)
    Bahamas = 44,
    /// Bahrain (BHR)
    Bahrain = 48,
    /// Bangladesh (BGD)
    Bangladesh = 50,
    /// Armenia (ARM)
    Armenia = 51,
    /// Barbados (BRB)
    Barbados = 52,
    /// Belgium (BEL)
    Belgium = 56,
    /// Bermuda (BMU)
    Bermuda = 60,
    /// Bhutan (BTN)
    Bhutan = 64,
    /// Bolivia, Plurinational State of (BOL)
    BoliviaPlurinationalStateOf = 68,
    /// Bosnia and Herzegovina (BIH)
    BosniaAndHerzegovina = 70,
    /// Botswana (BWA)
    Botswana = 72,
    /// Bouvet Island (BVT)
    BouvetIsland = 74,
    /// Brazil (BRA)
    Brazil = 76,
    /// Belize (BLZ)
    Belize = 84,
    /// British Indian Ocean Territory (IOT)
    BritishIndianOceanTerritory = 86,
    /// Solomon Islands (SLB)
    SolomonIslands = 90,
    /// Virgin Islands (British) (VGB)
    VirginIslandsBritish = 92,
    /// Brunei Darussalam (BRN)
    BruneiDarussalam = 96,
    /// Bulgaria (BGR)
    Bulgaria = 100,
    /// Myanmar (MMR)
    Myanmar = 104,
    /// Burundi (BDI)
    Burundi = 108,
    /// Belarus (BLR)
    Belarus = 112,
    /// Cambodia (KHM)
    Cambodia = 116,
    /// Cameroon (CMR)
    Cameroon = 120,
    /// Canada (CAN)
    Canada = 124,
    /// Cabo Verde (CPV)
    CaboVerde = 132,
    /// Cayman Islands (CYM)
    CaymanIslands = 136,
    /// Central African Republic (CAF)
    CentralAfricanRepublic = 140,
    /// Sri Lanka (LKA)
    SriLanka = 144,
    /// Chad (TCD)
    Chad = 148,
    /// Chile (CHL)
    Chile = 152,
    /// China (CHN)
    China = 156,
    /// Taiwan, Province of China (TWN)
    TaiwanProvinceOfChina = 158,
    /// Christmas Island (CXR)
    ChristmasIsland = 162,
    /// Cocos (Keeling) Islands (CCK)
    CocosKeelingIslands = 166,
    /// Colombia (COL)
    Colombia = 170,
    /// Comoros (COM)
    Comoros = 174,
    /// Mayotte (MYT)
    Mayotte = 175,
    /// Congo (COG)
    Congo = 178,
    /// Congo, Democratic Republic of the (COD)
    CongoDemocraticRepublicOfThe = 180,
    /// Cook Islands (COK)
    CookIslands = 184,
    /// Costa Rica (CRI)
    CostaRica = 188,
    /// Croatia (HRV)
    Croatia = 191,
    /// Cuba (CUB)
    Cuba = 192,
    /// Cyprus (CYP)
    Cyprus = 196,
    /// Czechia (CZE)
    Czechia = 203,
    /// Benin (BEN)
    Benin = 204,
    /// Denmark (DNK)
    Denmark = 208,
    /// Dominica (DMA)
    Dominica = 212,
    /// Dominican Republic (DOM)
    DominicanRepublic = 214,
    /// Ecuador (ECU)
    Ecuador = 218,
    /// El Salvador (SLV)
    ElSalvador = 222,
    /// Equatorial Guinea (GNQ)
    EquatorialGuinea = 226,
    /// Ethiopia (ETH)
    Ethiopia = 231,
    /// Eritrea (ERI)
    Eritrea = 232,
    /// Estonia (EST)
    Estonia = 233,
    /// Faroe Islands (FRO)
    FaroeIslands = 234,
    /// Falkland Islands (Malvinas) (FLK)
    FalklandIslandsMalvinas = 238,
    /// South Georgia and the South Sandwich Islands (SGS)
    SouthGeorgiaAndTheSouthSandwichIslands = 239,
    /// Fiji (FJI)
    Fiji = 242,
    /// Finland (FIN)
    Finland = 246,
    /// Åland Islands (ALA)
    AlandIslands = 248,
    /// France (FRA)
    France = 250,
    /// French Guiana (GUF)
    FrenchGuiana = 254,
    /// French Polynesia (PYF)
    FrenchPolynesia = 258,
    /// French Southern Territories (ATF)
    FrenchSouthernTerritories = 260,
    /// Djibouti (DJI)
    Djibouti = 262,
    /// Gabon (GAB)
    Gabon = 266,
    /// Georgia (GEO)
    Georgia = 268,
    /// Gambia (GMB)
    Gambia = 270,
    /// Palestine, State of (PSE)
    PalestineStateOf = 275,
    /// Germany (DEU)
    Germany = 276,
    /// Ghana (GHA)
    Ghana = 288,
    /// Gibraltar (GIB)
    Gibraltar = 292,
    /// Kiribati (KIR)
    Kiribati = 296,
    /// Greece (GRC)
    Greece = 300,
    /// Greenland (GRL)
    Greenland = 304,
    /// Grenada (GRD)
    Grenada = 308,
    /// Guadeloupe (GLP)
    Guadeloupe = 312,
    /// Guam (GUM)
    Guam = 316,
    /// Guatemala (GTM)
    Guatemala = 320,
    /// Guinea (GIN)
    Guinea = 324,
    /// Guyana (GUY)
    Guyana = 328,
    /// Haiti (HTI)
    Haiti = 332,
    /// Heard Island and McDonald Islands (HMD)
    HeardIslandAndMcDonaldIslands = 334,
    /// Holy See (VAT)
    HolySee = 336,
    /// Honduras (HND)
    Honduras = 340,
    /// Hong Kong (HKG)
    HongKong = 344,
    /// Hungary (HUN)
    Hungary = 348,
    /// Iceland (ISL)
    Iceland = 352,
    /// India (IND)
    India = 356,
    /// Indonesia (IDN)
    Indonesia = 360,
    /// Iran, Islamic Republic of (IRN)
    IranIslamicRepublicOf = 364,
    /// Iraq (IRQ)
    Iraq = 368,
    /// Ireland (IRL)
    Ireland = 372,
    /// Israel (ISR)
    Israel = 376,
    /// Italy (ITA)
    Italy = 380,
    /// Côte d'Ivoire (CIV)
    CoteDIvoire = 384,
    /// Jamaica (JAM)
    Jamaica = 388,
    /// Japan (JPN)
    Japan = 392,
    /// Kazakhstan (KAZ)
    Kazakhstan = 398,
    /// Jordan (JOR)
    Jordan = 400,
    /// Kenya (KEN)
    Kenya = 404,
    /// Korea, Democratic People's Republic of (PRK)
    KoreaDemocraticPeopleSRepublicOf = 408,
    /// Korea, Republic of (KOR)
    KoreaRepublicOf = 410,
    /// Kuwait (KWT)
    Kuwait = 414,
    /// Kyrgyzstan (KGZ)
    Kyrgyzstan = 417,
    /// Lao People's Democratic Republic (LAO)
    LaoPeopleSDemocraticRepublic = 418,
    /// Lebanon (LBN)
    Lebanon = 422,
    /// Lesotho (LSO)
    Lesotho = 426,
    /// Latvia (LVA)
    Latvia = 428,
    /// Liberia (LBR)
    Liberia = 430,
    /// Libya (LBY)
    Libya = 434,
    /// Liechtenstein (LIE)
    Liechtenstein = 438,
    /// Lithuania (LTU)
    Lithuania = 440,
    /// Luxembourg (LUX)
    Luxembourg = 442,
    /// Macao (MAC)
    Macao = 446,
    /// Madagascar (MDG)
    Madagascar = 450,
    /// Malawi (MWI)
    Malawi = 454,
    /// Malaysia (MYS)
    Malaysia = 458,
    /// Maldives (MDV)
    Maldives = 462,
    /// Mali (MLI)
    Mali = 466,
    /// Malta (MLT)
    Malta = 470,
    /// Martinique (MTQ)
    Martinique = 474,
    /// Mauritania (MRT)
    Mauritania = 478,
    /// Mauritius (MUS)
    Mauritius = 480,
    /// Mexico (MEX)
    Mexico = 484,
    /// Monaco (MCO)
    Monaco = 492,
    /// Mongolia (MNG)
    Mongolia = 496,
    /// Moldova, Republic of (MDA)
    MoldovaRepublicOf = 498,
    /// Montenegro (MNE)
    Montenegro = 499,
    /// Montserrat (MSR)
    Montserrat = 500,
    /// Morocco (MAR)
    Morocco = 504,
    /// Mozambique (MOZ)
    Mozambique = 508,
    /// Oman (OMN)
    Oman = 512,
    /// Namibia (NAM)
    Namibia = 516,
    /// Nauru (NRU)
    Nauru = 520,
    /// Nepal (NPL)
    Nepal = 524,
    /// Netherlands, Kingdom of the (NLD)
    NetherlandsKingdomOfThe = 528,
    /// Curaçao (CUW)
    Curacao = 531,
    /// Aruba (ABW)
    Aruba = 533,
    /// Sint Maarten (Dutch part) (SXM)
    SintMaartenDutchPart = 534,
    /// Bonaire, Sint Eustatius and Saba (BES)
    BonaireSintEustatiusAndSaba = 535,
    /// New Caledonia (NCL)
    NewCaledonia = 540,
    /// Vanuatu (VUT)
    Vanuatu = 548,
    /// New Zealand (NZL)
    NewZealand = 554,
    /// Nicaragua (NIC)
    Nicaragua = 558,
    /// Niger (NER)
    Niger = 562,
    /// Nigeria (NGA)
    Nigeria = 566,
    /// Niue (NIU)
    Niue = 570,
    /// Norfolk Island (NFK)
    NorfolkIsland = 574,
    /// Norway (NOR)
    Norway = 578,
    /// Northern Mariana Islands (MNP)
    NorthernMarianaIslands = 580,
    /// United States Minor Outlying Islands (UMI)
    UnitedStatesMinorOutlyingIslands = 581,
    /// Micronesia, Federated States of (FSM)
    MicronesiaFederatedStatesOf = 583,
    /// Marshall Islands (MHL)
    MarshallIslands = 584,
    /// Palau (PLW)
    Palau = 585,
    /// Pakistan (PAK)
    Pakistan = 586,
    /// Panama (PAN)
    Panama = 591,
    /// Papua New Guinea (PNG)
    PapuaNewGuinea = 598,
    /// Paraguay (PRY)
    Paraguay = 600,
    /// Peru (PER)
    Peru = 604,
    /// Philippines (PHL)
    Philippines = 608,
    /// Pitcairn (PCN)
    Pitcairn = 612,
    /// Poland (POL)
    Poland = 616,
    /// Portugal (PRT)
    Portugal = 620,
    /// Guinea-Bissau (GNB)
    GuineaBissau = 624,
    /// Timor-Leste (TLS)
    TimorLeste = 626,
    /// Puerto Rico (PRI)
    PuertoRico = 630,
    /// Qatar (QAT)
    Qatar = 634,
    /// Réunion (REU)
    Reunion = 638,
    /// Romania (ROU)
    Romania = 642,
    /// Russian Federation (RUS)
    RussianFederation = 643,
    /// Rwanda (RWA)
    Rwanda = 646,
    /// Saint Barthélemy (BLM)
    SaintBarthelemy = 652,
    /// Saint Helena, Ascension and Tristan da Cunha (SHN)
    SaintHelenaAscensionAndTristanDaCunha = 654,
    /// Saint Kitts and Nevis (KNA)
    SaintKittsAndNevis = 659,
    /// Anguilla (AIA)
    Anguilla = 660,
    /// Saint Lucia (LCA)
    SaintLucia = 662,
    /// Saint Martin (French part) (MAF)
    SaintMartinFrenchPart = 663,
    /// Saint Pierre and Miquelon (SPM)
    SaintPierreAndMiquelon = 666,
    /// Saint Vincent and the Grenadines (VCT)
    SaintVincentAndTheGrenadines = 670,
    /// San Marino (SMR)
    SanMarino = 674,
    /// Sao Tome and Principe (STP)
    SaoTomeAndPrincipe = 678,
    /// Saudi Arabia (SAU)
    SaudiArabia = 682,
    /// Senegal (SEN)
    Senegal = 686,
    /// Serbia (SRB)
    Serbia = 688,
    /// Seychelles (SYC)
    Seychelles = 690,
    /// Sierra Leone (SLE)
    SierraLeone = 694,
    /// Singapore (SGP)
    Singapore = 702,
    /// Slovakia (SVK)
    Slovakia = 703,
    /// Viet Nam (VNM)
    VietNam = 704,
    /// Slovenia (SVN)
    Slovenia = 705,
    /// Somalia (SOM)
    Somalia = 706,
    /// South Africa (ZAF)
    SouthAfrica = 710,
    /// Zimbabwe (ZWE)
    Zimbabwe = 716,
    /// Spain (ESP)
    Spain = 724,
    /// South Sudan (SSD)
    SouthSudan = 728,
    /// Sudan (SDN)
    Sudan = 729,
    /// Western Sahara (ESH)
    WesternSahara = 732,
    /// Suriname (SUR)
    Suriname = 740,
    /// Svalbard and Jan Mayen (SJM)
    SvalbardAndJanMayen = 744,
    /// Eswatini (SWZ)
    Eswatini = 748,
    /// Sweden (SWE)
    Sweden = 752,
    /// Switzerland (CHE)
    Switzerland = 756,
    /// Syrian Arab Republic (SYR)
    SyrianArabRepublic = 760,
    /// Tajikistan (TJK)
    Tajikistan = 762,
    /// Thailand (THA)
    Thailand = 764,
    /// Togo (TGO)
    Togo = 768,
    /// Tokelau (TKL)
    Tokelau = 772,
    /// Tonga (TON)
    Tonga = 776,
    /// Trinidad and Tobago (TTO)
    TrinidadAndTobago = 780,
    /// United Arab Emirates (ARE)
    UnitedArabEmirates = 784,
    /// Tunisia (TUN)
    Tunisia = 788,
    /// Türkiye (TUR)
    Turkiye = 792,
    /// Turkmenistan (TKM)
    Turkmenistan = 795,
    /// Turks and Caicos Islands (TCA)
    TurksAndCaicosIslands = 796,
    /// Tuvalu (TUV)
    Tuvalu = 798,
    /// Uganda (UGA)
    Uganda = 800,
    /// Ukraine (UKR)
    Ukraine = 804,
    /// North Macedonia (MKD)
    NorthMacedonia = 807,
    /// Egypt (EGY)
    Egypt = 818,
    /// United Kingdom of Great Britain and Northern Ireland (GBR)
    UnitedKingdomOfGreatBritainAndNorthernIreland = 826,
    /// Guernsey (GGY)
    Guernsey = 831,
    /// Jersey (JEY)
    Jersey = 832,
    /// Isle of Man (IMN)
    IsleOfMan = 833,
    /// Tanzania, United Republic of (TZA)
    TanzaniaUnitedRepublicOf = 834,
    /// United States of America (USA)
    UnitedStatesOfAmerica = 840,
    /// Virgin Islands (U.S.) (VIR)
    VirginIslandsUS = 850,
    /// Burkina Faso (BFA)
    BurkinaFaso = 854,
    /// Uruguay (URY)
    Uruguay = 858,
    /// Uzbekistan (UZB)
    Uzbekistan = 860,
    /// Venezuela, Bolivarian Republic of (VEN)
    VenezuelaBolivarianRepublicOf = 862,
    /// Wallis and Futuna (WLF)
    WallisAndFutuna = 876,
    /// Samoa (WSM)
    Samoa = 882,
    /// Yemen (YEM)
    Yemen = 887,
    /// Zambia (ZMB)
    Zambia = 894,
}
