[package]
name = "stwo-sha256"
version.workspace = true
edition.workspace = true

[dependencies]
air-core = { path = "../air-core" }
stwo = { workspace = true }
stwo-constraint-framework = { workspace = true }
num-traits = { workspace = true }
rand = "0.8"
rayon = "1"
serde = { workspace = true }

[dev-dependencies]
sha2 = "0.10"
hex = "0.4"
bincode = "1"

[lints]
workspace = true
