//! Limb-decomposed P-256 curve constants.
//!
//! Provides `p`, `n`, `b`, `G`, `[2]G`, `[3]G` (and helpers) as
//! `[i64; N_LIMBS]` arrays in the 20×13-bit representation used by the AIR.
//! `a = −3` is a small constant and does not need a precomputed limb form.
//!
//! Every constant exposed by this module is generated by code and verified
//! against the source u64 representation in [`crate::constants`]. The
//! generated arrays are intended to be `include!`-able into the AIR crate via
//! `build.rs`.

use crate::constants::{LIMB_BITS, N_LIMBS, P256_GX, P256_GY, P256_MODULUS, P256_ORDER};

const P256_G2X: [u64; 4] = [
    0xA60B_48FC_4766_9978,
    0xC089_69E2_77F2_1B35,
    0x8A52_3803_04B5_1AC3,
    0x7CF2_7B18_8D03_4F7E,
];

const P256_G2Y: [u64; 4] = [
    0x9E04_B79D_2278_73D1,
    0xBA7D_ADE6_3CE9_8229,
    0x293D_9AC6_9F74_30DB,
    0x0777_5510_DB8E_D040,
];

const P256_G3X: [u64; 4] = [
    0xFB41_661B_C6E7_FD6C,
    0xE6C6_B721_EFAD_A985,
    0xC8F7_EF95_1D4B_F165,
    0x5ECB_E4D1_A633_0A44,
];

const P256_G3Y: [u64; 4] = [
    0x9A79_B127_A27D_5032,
    0xD82A_B036_384F_B83D,
    0x374B_06CE_1A64_A2EC,
    0x8734_640C_4998_FF7E,
];

/// Decompose a little-endian `u64` array into `N_LIMBS` 13-bit limbs.
///
/// Bits beyond position 256 are discarded; the canonical P-256 field elements
/// fit in 256 bits, so the top limb stores at most 9 bits.
pub fn decompose_256_to_limbs(le_u64: &[u64; 4]) -> [i64; N_LIMBS] {
    let mut out = [0i64; N_LIMBS];
    for (i, slot) in out.iter_mut().enumerate() {
        let bit_pos = i * LIMB_BITS;
        let mut limb: u64 = 0;
        for bit in 0..LIMB_BITS {
            let g = bit_pos + bit;
            if g >= 256 {
                break;
            }
            let word = g / 64;
            let off = g % 64;
            if (le_u64[word] >> off) & 1 == 1 {
                limb |= 1u64 << bit;
            }
        }
        *slot = limb as i64;
    }
    out
}

/// `p` in 20×13-bit limb form.
pub fn p_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_MODULUS)
}

/// `n` in 20×13-bit limb form.
pub fn n_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_ORDER)
}

/// `G.x` in 20×13-bit limb form.
pub fn gx_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_GX)
}

/// `G.y` in 20×13-bit limb form.
pub fn gy_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_GY)
}

/// `[2]G` x-coordinate in 20×13-bit limb form.
pub fn g2x_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_G2X)
}

/// `[2]G` y-coordinate in 20×13-bit limb form.
pub fn g2y_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_G2Y)
}

/// `[3]G` x-coordinate in 20×13-bit limb form.
pub fn g3x_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_G3X)
}

/// `[3]G` y-coordinate in 20×13-bit limb form.
pub fn g3y_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_G3Y)
}

/// P-256 curve parameter `b`. Hex from the AIR spec:
/// `0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b`.
pub const P256_B: [u64; 4] = [
    0x3BCE_3C3E_27D2_604B,
    0x651D_06B0_CC53_B0F6,
    0xB3EB_BD55_7698_86BC,
    0x5AC6_35D8_AA3A_93E7,
];

/// `b` in 20×13-bit limb form.
pub fn b_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_B)
}

#[cfg(test)]
mod tests {
    use super::*;
    use p256::elliptic_curve::group::Group;
    use p256::elliptic_curve::sec1::ToEncodedPoint;
    use p256::{AffinePoint, ProjectivePoint};

    #[test]
    fn limb_decomposition_roundtrips_for_p() {
        assert_eq!(limbs_to_le_u64s(&p_limbs()), P256_MODULUS);
    }

    #[test]
    fn p_top_limb_fits_9_bits() {
        // p < 2^256 implies p_limbs[19] < 2^9.
        let limbs = p_limbs();
        assert!(limbs[N_LIMBS - 1] < (1i64 << 9));
    }

    #[test]
    fn each_limb_within_13_bits() {
        for arr in [
            p_limbs(),
            n_limbs(),
            gx_limbs(),
            gy_limbs(),
            g2x_limbs(),
            g2y_limbs(),
            g3x_limbs(),
            g3y_limbs(),
            b_limbs(),
        ] {
            for limb in arr {
                assert!(
                    limb >= 0 && limb < (1i64 << LIMB_BITS),
                    "limb {limb} out of [0, 2^{LIMB_BITS})"
                );
            }
        }
    }

    #[test]
    fn generator_multiples_match_rustcrypto_reference() {
        let g = ProjectivePoint::generator();
        assert_eq!(le_u64s_to_be_bytes(&P256_G2X), affine_x_bytes(g + g));
        assert_eq!(le_u64s_to_be_bytes(&P256_G2Y), affine_y_bytes(g + g));
        assert_eq!(le_u64s_to_be_bytes(&P256_G3X), affine_x_bytes(g + g + g));
        assert_eq!(le_u64s_to_be_bytes(&P256_G3Y), affine_y_bytes(g + g + g));
    }

    #[test]
    fn generator_multiple_limbs_roundtrip_to_raw_constants() {
        for (limbs, raw) in [
            (g2x_limbs(), P256_G2X),
            (g2y_limbs(), P256_G2Y),
            (g3x_limbs(), P256_G3X),
            (g3y_limbs(), P256_G3Y),
        ] {
            assert_eq!(limbs_to_le_u64s(&limbs), raw);
        }
    }

    fn affine_x_bytes(point: ProjectivePoint) -> [u8; 32] {
        let encoded = AffinePoint::from(point).to_encoded_point(false);
        field_bytes_to_array(encoded.x().expect("uncompressed point has x"))
    }

    fn affine_y_bytes(point: ProjectivePoint) -> [u8; 32] {
        let encoded = AffinePoint::from(point).to_encoded_point(false);
        field_bytes_to_array(encoded.y().expect("uncompressed point has y"))
    }

    fn field_bytes_to_array(bytes: &[u8]) -> [u8; 32] {
        let mut out = [0u8; 32];
        out.copy_from_slice(bytes);
        out
    }

    fn le_u64s_to_be_bytes(words: &[u64; 4]) -> [u8; 32] {
        let mut bytes = [0u8; 32];
        for (i, word) in words.iter().enumerate() {
            bytes[24 - 8 * i..32 - 8 * i].copy_from_slice(&word.to_be_bytes());
        }
        bytes
    }

    fn limbs_to_le_u64s(limbs: &[i64; N_LIMBS]) -> [u64; 4] {
        let mut words = [0u64; 4];
        for (i, &limb) in limbs.iter().enumerate() {
            let bit_pos = i * LIMB_BITS;
            for bit in 0..LIMB_BITS {
                let global_bit = bit_pos + bit;
                if global_bit >= 256 {
                    break;
                }
                if ((limb as u64) >> bit) & 1 == 1 {
                    words[global_bit / 64] |= 1u64 << (global_bit % 64);
                }
            }
        }
        words
    }
}
