//! Limb-decomposed P-256 curve constants.
//!
//! Provides `p`, `n`, `b`, `G`, `[2]G`, `[3]G` (and helpers) as
//! `[i64; N_LIMBS]` arrays in the 20×13-bit representation used by the AIR.
//! `a = −3` is a small constant and does not need a precomputed limb form.
//!
//! Every constant exposed by this module is generated by code and verified
//! against the source u64 representation in [`crate::constants`]. The
//! generated arrays are intended to be `include!`-able into the AIR crate via
//! `build.rs`.

use crate::constants::{LIMB_BITS, N_LIMBS, P256_GX, P256_GY, P256_MODULUS, P256_ORDER};

/// Decompose a little-endian `u64` array into `N_LIMBS` 13-bit limbs.
///
/// Bits beyond position 256 are discarded; the canonical P-256 field elements
/// fit in 256 bits, so the top limb stores at most 9 bits.
pub fn decompose_256_to_limbs(le_u64: &[u64; 4]) -> [i64; N_LIMBS] {
    let mut out = [0i64; N_LIMBS];
    for (i, slot) in out.iter_mut().enumerate() {
        let bit_pos = i * LIMB_BITS;
        let mut limb: u64 = 0;
        for bit in 0..LIMB_BITS {
            let g = bit_pos + bit;
            if g >= 256 {
                break;
            }
            let word = g / 64;
            let off = g % 64;
            if (le_u64[word] >> off) & 1 == 1 {
                limb |= 1u64 << bit;
            }
        }
        *slot = limb as i64;
    }
    out
}

/// `p` in 20×13-bit limb form.
pub fn p_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_MODULUS)
}

/// `n` in 20×13-bit limb form.
pub fn n_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_ORDER)
}

/// `G.x` in 20×13-bit limb form.
pub fn gx_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_GX)
}

/// `G.y` in 20×13-bit limb form.
pub fn gy_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_GY)
}

/// `[2]G` x-coordinate in 20×13-bit limb form. Computed once at startup from
/// `G` via a reference Fp arithmetic implementation.
pub fn g2x_limbs() -> [i64; N_LIMBS] {
    todo!("Compute [2]G via affine doubling on P-256 using a big-int reference, then decompose.")
}

/// `[2]G` y-coordinate in 20×13-bit limb form.
pub fn g2y_limbs() -> [i64; N_LIMBS] {
    todo!("Compute [2]G via affine doubling on P-256 using a big-int reference, then decompose.")
}

/// `[3]G` x-coordinate in 20×13-bit limb form.
pub fn g3x_limbs() -> [i64; N_LIMBS] {
    todo!("Compute [3]G = G + [2]G via affine addition using a big-int reference, then decompose.")
}

/// `[3]G` y-coordinate in 20×13-bit limb form.
pub fn g3y_limbs() -> [i64; N_LIMBS] {
    todo!("Compute [3]G = G + [2]G via affine addition using a big-int reference, then decompose.")
}

/// P-256 curve parameter `b`. Hex from the AIR spec:
/// `0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b`.
pub const P256_B: [u64; 4] = [
    0x3BCE_3C3E_27D2_604B,
    0x651D_06B0_CC53_B0F6,
    0xB3EB_BD55_7698_86BC,
    0x5AC6_35D8_AA3A_93E7,
];

/// `b` in 20×13-bit limb form.
pub fn b_limbs() -> [i64; N_LIMBS] {
    decompose_256_to_limbs(&P256_B)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn limb_decomposition_roundtrips_for_p() {
        let limbs = p_limbs();
        // Recompose and check we recover P256_MODULUS up to 256 bits.
        let mut recomposed = [0u64; 4];
        for (i, &limb) in limbs.iter().enumerate() {
            let limb_u = limb as u64;
            let bit_pos = i * LIMB_BITS;
            for bit in 0..LIMB_BITS {
                let g = bit_pos + bit;
                if g >= 256 {
                    break;
                }
                if (limb_u >> bit) & 1 == 1 {
                    recomposed[g / 64] |= 1u64 << (g % 64);
                }
            }
        }
        assert_eq!(recomposed, P256_MODULUS);
    }

    #[test]
    fn p_top_limb_fits_9_bits() {
        // p < 2^256 implies p_limbs[19] < 2^9.
        let limbs = p_limbs();
        assert!(limbs[N_LIMBS - 1] < (1i64 << 9));
    }

    #[test]
    fn each_limb_within_13_bits() {
        for arr in [p_limbs(), n_limbs(), gx_limbs(), gy_limbs(), b_limbs()] {
            for limb in arr {
                assert!(
                    limb >= 0 && limb < (1i64 << LIMB_BITS),
                    "limb {limb} out of [0, 2^{LIMB_BITS})"
                );
            }
        }
    }
}
