//! Preprocessed selector lookup tables.
//!
//! The AIR consumes three small preprocessed tables, each generated here and
//! cross-checked against the chain semantics derivation in the spec
//! (section "Chain semantics: the recoding identity"):
//!
//! - [`selector4x4`]: `(a, b) ∈ {0,1,2,3}² → selector = a + 4·b`. 16 rows.
//!   Enforces that each chunk pair packs correctly.
//! - [`selector16_decode`]: `selector ∈ 0..16 → (base_index, neg_bit)`.
//!   16 rows. Maps each chain selector to one of `Base[0..7]` plus a
//!   conditional negation. See AIR spec L1174 for the full mapping.
//! - [`final_selector`]: `(msb1, msb2) ∈ {0,1}² → (selector_final, init_base_index)`.
//!   4 rows. Used for MSB initialization. See AIR spec L1311.
//!
//! Every table is generated by code (single source of truth), then verified
//! against an independent test that walks the chain semantics for small
//! `(s1, s2_abs)` pairs and confirms `Acc_final = R3`.

/// One row of the `Selector4x4` table: `selector = a + 4 · b`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Selector4x4Row {
    pub a: u8,
    pub b: u8,
    pub selector: u8,
}

/// Generate the 16-row `Selector4x4` table.
pub fn selector4x4() -> [Selector4x4Row; 16] {
    let mut out = [Selector4x4Row {
        a: 0,
        b: 0,
        selector: 0,
    }; 16];
    let mut i = 0usize;
    for b in 0u8..4 {
        for a in 0u8..4 {
            out[i] = Selector4x4Row {
                a,
                b,
                selector: a + 4 * b,
            };
            i += 1;
        }
    }
    out
}

/// One row of the `Selector16Decode` table: a chain selector value maps to a
/// base-table index plus a conditional negation bit.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Selector16DecodeRow {
    pub selector: u8,
    pub base_index: u8,
    pub neg_bit: u8,
}

/// Generate the 16-row `Selector16Decode` table per AIR spec L1174:
///
/// ```text
/// selector  0 -> (Base[7], neg=1)     = -(3P + 3R)
/// selector  1 -> (Base[6], neg=1)     = -(P + 3R)
/// selector  2 -> (Base[5], neg=0)     =   P - 3R
/// selector  3 -> (Base[4], neg=0)     =  3P - 3R
/// selector  4 -> (Base[3], neg=1)     = -(3P + R)
/// selector  5 -> (Base[2], neg=1)     = -(P + R)
/// selector  6 -> (Base[1], neg=0)     =   P - R
/// selector  7 -> (Base[0], neg=0)     =  3P - R
/// selector  8 -> (Base[0], neg=1)     = -(3P - R)
/// selector  9 -> (Base[1], neg=1)     = -(P - R)
/// selector 10 -> (Base[2], neg=0)     =   P + R
/// selector 11 -> (Base[3], neg=0)     =  3P + R
/// selector 12 -> (Base[4], neg=1)     = -(3P - 3R)
/// selector 13 -> (Base[5], neg=1)     = -(P - 3R)
/// selector 14 -> (Base[6], neg=0)     =   P + 3R
/// selector 15 -> (Base[7], neg=0)     =  3P + 3R
/// ```
pub fn selector16_decode() -> [Selector16DecodeRow; 16] {
    const T: [(u8, u8); 16] = [
        (7, 1),
        (6, 1),
        (5, 0),
        (4, 0),
        (3, 1),
        (2, 1),
        (1, 0),
        (0, 0),
        (0, 1),
        (1, 1),
        (2, 0),
        (3, 0),
        (4, 1),
        (5, 1),
        (6, 0),
        (7, 0),
    ];
    let mut out = [Selector16DecodeRow {
        selector: 0,
        base_index: 0,
        neg_bit: 0,
    }; 16];
    let mut i = 0usize;
    while i < 16 {
        out[i] = Selector16DecodeRow {
            selector: i as u8,
            base_index: T[i].0,
            neg_bit: T[i].1,
        };
        i += 1;
    }
    out
}

/// One row of the `FinalSelector` table: MSB-bit pair to selector value and
/// the `Base[init_base_index]` directly loaded for `Acc_0`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FinalSelectorRow {
    pub msb1: u8,
    pub msb2: u8,
    pub selector_final: u8,
    pub init_base_index: u8,
}

/// Generate the 4-row `FinalSelector` table per AIR spec L1311:
///
/// ```text
/// (msb1, msb2) | selector_final | init_base_index | Acc_0
///   (0, 0)     |      5         |       2         |  P  + R
///   (1, 0)     |      6         |       3         | 3P  + R
///   (0, 1)     |      9         |       6         |  P  + 3R
///   (1, 1)     |     10         |       7         | 3P  + 3R
/// ```
pub fn final_selector() -> [FinalSelectorRow; 4] {
    [
        FinalSelectorRow {
            msb1: 0,
            msb2: 0,
            selector_final: 5,
            init_base_index: 2,
        },
        FinalSelectorRow {
            msb1: 1,
            msb2: 0,
            selector_final: 6,
            init_base_index: 3,
        },
        FinalSelectorRow {
            msb1: 0,
            msb2: 1,
            selector_final: 9,
            init_base_index: 6,
        },
        FinalSelectorRow {
            msb1: 1,
            msb2: 1,
            selector_final: 10,
            init_base_index: 7,
        },
    ]
}

/// Cross-check the selector tables against the recoding identity.
///
/// Enumerate small `(s1, s2_abs)` values, run the chain semantics symbolically
/// using these tables (MSB init → 63 steps → LSB correction), and assert the
/// resulting accumulator equals `R3 = [3]·H_signed` for every input. Required
/// before the tables are baked into the AIR.
pub fn verify_recoding_identity() -> Result<(), &'static str> {
    todo!(
        "Run the chain symbolically over small (s1, s2_abs) pairs (e.g., s1 < 2^16, s2_abs < 2^16) \
         using the selector tables above. Apply the digit map d(a) = 2a - 3 and the MSB d_msb(b) = 1 + 2b, \
         then verify Acc_after_LSB = [s1]·P + [s2_abs]·R + [3]·R for symbolic P and R. \
         Mismatch on any input means the tables are wrong."
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn selector4x4_is_injective_and_covers_all_selectors() {
        let table = selector4x4();
        let mut seen = [false; 16];
        for row in table.iter() {
            assert!(row.a < 4 && row.b < 4);
            assert_eq!(row.selector as u32, row.a as u32 + 4 * row.b as u32);
            assert!(
                !seen[row.selector as usize],
                "duplicate selector {}",
                row.selector
            );
            seen[row.selector as usize] = true;
        }
        assert!(seen.iter().all(|&s| s), "missing selector value");
    }

    #[test]
    fn selector16_decode_is_total_and_consistent() {
        let table = selector16_decode();
        for (i, row) in table.iter().enumerate() {
            assert_eq!(row.selector as usize, i);
            assert!(row.base_index < 8);
            assert!(row.neg_bit < 2);
        }
        // Mirror symmetry: selector s and selector (15 - s) should pick the same
        // base index with opposite neg_bit (signs flip across the table midpoint).
        for s in 0..8u8 {
            assert_eq!(
                table[s as usize].base_index,
                table[(15 - s) as usize].base_index
            );
            assert_ne!(table[s as usize].neg_bit, table[(15 - s) as usize].neg_bit);
        }
    }

    #[test]
    fn final_selector_matches_spec_mapping() {
        let table = final_selector();
        assert_eq!(table[0].selector_final, 5);
        assert_eq!(table[0].init_base_index, 2);
        assert_eq!(table[1].selector_final, 6);
        assert_eq!(table[1].init_base_index, 3);
        assert_eq!(table[2].selector_final, 9);
        assert_eq!(table[2].init_base_index, 6);
        assert_eq!(table[3].selector_final, 10);
        assert_eq!(table[3].init_base_index, 7);
    }
}
