[package]
name = "predicates"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = ["stwo/std", "stwo-constraint-framework/std"]

[dependencies]
air-core = { path = "../air-core" }
stwo = { workspace = true }
stwo-constraint-framework = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }
rand = "0.8"
thiserror = "2.0.18"
