[package]
name = "stwo-p256"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["stwo/std", "stwo-constraint-framework/std"]

[dependencies]
stwo = { workspace = true, features = ["parallel"] }
stwo-constraint-framework = { workspace = true, features = ["parallel"] }
stwo-p256-utils = { path = "../stwo-p256-utils" }
rayon = "1"
itertools = { version = "0.12", default-features = false, features = ["use_alloc"] }
num-bigint = "0.4"
num-integer = "0.1"
num-traits = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
p256 = { version = "0.13", features = ["ecdsa"] }
ecdsa = { version = "0.16", features = ["signing", "verifying"] }
rand = "0.8"
hex = "0.4"
sha2 = "0.10"

[lints]
workspace = true
